### PR TITLE
Dynamic field id

### PR DESCRIPTION
**Pull request by tboulogne**

### CODE REVIEW

**Comment by linevych** [comment]
Hi @tboulogne and thanks for your PR. But swapping `id` with `pk` will do the trick for you. Check out the [Django docs](https://docs.djangoproject.com/en/2.2/topics/db/queries/#the-pk-lookup-shortcut).

Can you update your PR, please?

**Comment by linevych** [comment]
I did some refactoring and improvements in #6 and also replaced `id` with `pk`. Thanks for poiting out the problem.

**Comment by tboulogne** [comment]
Hi

It’s not a pk problem.
Imagine id is prefixed for each model. For exemple ren_id for a rental model, pk does not works.

Thierry BOULOGNE
06 43 18 31 19

**Comment by tboulogne** [comment]
Sorry my answer was so speed
I will try your mods.

Thierry BOULOGNE
06 43 18 31 19

**Comment by linevych** [comment]
>  For exemple ren_id for a rental model, pk does not works.

Sorry, I don't understand can you give me a sample of code?

If you have model:

```
class MyModel(models.Model):
    ren_id  = models.AutoField(primary_key=True)
```

Then both `MyModel.objects.get(ren_id=1)` and `MyModel.objects.get(pk=1)` should work.

**Pull request closed without merging**
